version: '3.1'

services:

  influxdb:
    image: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: szit
      DOCKER_INFLUXDB_INIT_PASSWORD: 11111111
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mytoken
    volumes:
       - /data/dc-yaml/influxdb2/data:/var/lib/influxdb2
       - /data/dc-yaml/influxdb2/config:/etc/influxdb2
    ports:
      - 8087:8087

